@startuml Activity_Service_Admin
!theme plain

|Admin|
start
:Quản lý dịch vụ;

|System|
:Kiểm tra điều kiện và thực hiện CRUD;
if (Thành công?) then (không)
    :Hiển thị lỗi;
else (có)
    :Thực hiện thành công;
endif

|Admin|
:Hiển thị kết quả;
stop

@enduml

