@startuml Activity_Room_Customer
!theme plain

|Customer|
start
:Xem danh sách phòng;

|System|
:Lấy danh sách phòng;
if (Có phòng?) then (không)
    :Không có phòng;
else (có)
    :Hiển thị danh sách phòng;
endif

|Customer|
:Hiển thị kết quả;
stop

@enduml
