@startuml Activity_Service_Staff
!theme plain

|Staff|
start
:Quản lý service bookings;

|System|
:Kiểm tra điều kiện và thực hiện CRUD;
if (Thành công?) then (không)
    :Hiển thị lỗi;
else (có)
    :Thực hiện thành công;
endif

|Staff|
:Hiển thị kết quả;
stop

@enduml

