@startuml Activity_Chat_Staff
!theme plain

|Admin/Staff|
start
:Quản lý chat;

|System|
:Kiểm tra điều kiện và thực hiện CRUD;
if (Thành công?) then (không)
    :Hiển thị lỗi;
else (có)
    :Thực hiện thành công;
endif

|Admin/Staff|
:Hiển thị kết quả;
stop

@enduml

