@startuml Activity_Room_Staff
!theme plain

|Staff|
start
:Xem phòng;

|System|
:Kiểm tra điều kiện và thực hiện CRUD;
if (Thành công?) then (không)
    :Hiển thị lỗi;
else (có)
    :Thực hiện thành công;
endif

|Staff|
:Hiển thị kết quả (read-only);
stop

@enduml
