@startuml Activity_Chat_Customer
!theme plain

|Customer|
start
:Quản lý chat;

|System|
:Kiểm tra điều kiện và thực hiện CRUD;
if (Thành công?) then (không)
    :Hiển thị lỗi;
else (có)
    :Thực hiện thành công;
endif

|Customer|
:Hiển thị kết quả;
stop

@enduml

