
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "email": "staff@gmail.com",
    "password": "123456"
}

### get profile
GET http://localhost:8080/api/v1/auth/get-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTE5NDQyZmYyY2UwOTdkN2QzMTY1N2IiLCJlbWFpbCI6InN0YWZmQGdtYWlsLmNvbSIsImlhdCI6MTc2MzI2MzU1OSwiZXhwIjoxNzYzMzQ5OTU5fQ.Xb0MJMBJ8_KcfcKEZSAAWL-3TWsITo9OKBHk81ctADc
