@startuml Algorithm - Xem danh sách địa điểm
!theme plain
title Sơ đồ thuật toán - Xem danh sách địa điểm

start
:Input: filters (type, enabled=true);
:Lấy danh sách locations với enabled = true;
:Áp dụng filters;
:Sắp xếp theo name ASC;
:Phân trang;
:Return danh sách locations;
stop
@enduml

